# name of the software
name: SwpWallet.js

project:
    version: 0.1.3
    download_url: https://github.com/Swipetech/swp-wallet-node-sdk

links:
    header:
      - title: GitHub
        url: https://github.com/Swipetech/swp-wallet-node-sdk
    footer:
      - title: GitHub
        url: https://github.com/Swipetech/swp-wallet-node-sdk
      - title: Issues
        url: https://github.com/Swipetech/swp-wallet-node-sdk/issues?state=open

ui:
    header:
        color1: "#f7f7f9"
        color2: "#f7f7f9"
        trianglify: false

social:
    github:
        user: Swipetech
        repo: swp-wallet-node-sdk
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - lib
    - .merlin
    - node_modules
    - .bsb.lock
    - .vscode