// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Js_math from "bs-platform/lib/es6/js_math.js";
import * as CryptoJs from "crypto-js";
import * as EncBase64 from "crypto-js/enc-base64";

function setHeaders(apiKey, secret, path, body, headers) {
  var timestamp = String(Js_math.floor(Date.now() / 1000.0));
  var strBody = body ? body[0] : "";
  var hmac = CryptoJs.HmacSHA384(timestamp + (path + strBody), secret);
  var signature = EncBase64.stringify(hmac);
  headers["X-Swp-Api-Key"] = apiKey;
  headers["X-Swp-Signature"] = signature;
  headers["X-Swp-Timestamp"] = timestamp;
  return /* () */0;
}

export {
  setHeaders ,
  
}
/* crypto-js Not a pure module */
