// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE


var host = "http://localhost:8080";

var sandboxHost = "http://localhost:8080";

export {
  host ,
  sandboxHost ,
  
}
/* No side effect */
