// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE


var host = "https://pay.swipetech.io";

var sandboxHost = "https://pay.sandbox.swipetech.io";

export {
  host ,
  sandboxHost ,
  
}
/* No side effect */
