// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as Auth$SwpWalletSdk from "./Auth.js";
import * as Service$SwpWalletSdk from "./Service.js";

function get(headers, setAuthHeaders, debug, sandbox, path) {
  Curry._3(setAuthHeaders, path, /* None */0, headers);
  return Service$SwpWalletSdk.get(headers, debug, sandbox, path);
}

function post(headers, body, setAuthHeaders, debug, sandbox, path) {
  Curry._3(setAuthHeaders, path, Js_primitive.undefined_to_opt(JSON.stringify(body)), headers);
  return Service$SwpWalletSdk.post(headers, body, debug, sandbox, path);
}

var Options = /* module */[];

var accounts = "/accounts";

function getAccount(id) {
  return "" + (String(accounts) + ("/" + (String(id) + "")));
}

var organizations = "/organizations";

var assets = "" + (String(organizations) + "/assets");

var payments = "/operations/payments";

var Routes = /* module */[
  /* accounts */accounts,
  /* getAccount */getAccount,
  /* organizations */organizations,
  /* assets */assets,
  /* payments */payments
];

function make(prim, prim$1, prim$2, prim$3, prim$4, prim$5) {
  return {
          createAccount: prim,
          getAccount: prim$1,
          getAllAccounts: prim$2,
          getAssets: prim$3,
          getOrganization: prim$4,
          makePayment: prim$5
        };
}

var Endpoints = /* module */[
  /* Routes */Routes,
  /* make */make
];

function init(options) {
  var match = options.language;
  var language = match !== undefined ? match : "pt-br";
  var headers = { };
  headers["Content-Type"] = "application/json";
  headers["Accept-Language"] = language;
  var partial_arg = options.secret;
  var partial_arg$1 = options.apiKey;
  var partialSetAuthHeaders = function (param, param$1, param$2) {
    return Auth$SwpWalletSdk.setHeaders(partial_arg$1, partial_arg, param, param$1, param$2);
  };
  var partial_arg$2 = Js_primitive.undefined_to_opt(options.sandbox);
  var partial_arg$3 = Js_primitive.undefined_to_opt(options.debug);
  var getRoute = function (param) {
    return get(headers, partialSetAuthHeaders, partial_arg$3, partial_arg$2, param);
  };
  var arg = options.debug;
  var arg$1 = arg === undefined ? /* None */0 : [arg];
  var arg$2 = options.sandbox;
  var arg$3 = arg$2 === undefined ? /* None */0 : [arg$2];
  var postToRoute = function (param) {
    return (function (param$1) {
        var param$2 = param;
        var param$3 = partialSetAuthHeaders;
        var param$4 = arg$1;
        var param$5 = arg$3;
        var param$6 = param$1;
        return post(headers, param$2, param$3, param$4, param$5, param$6);
      });
  };
  return make((function () {
                return postToRoute(/* None */0)(accounts);
              }), (function (id) {
                return Curry._1(getRoute, getAccount(id));
              }), (function () {
                return Curry._1(getRoute, accounts);
              }), (function () {
                return Curry._1(getRoute, assets);
              }), (function () {
                return Curry._1(getRoute, organizations);
              }), (function (body) {
                return postToRoute(/* Some */[body])(payments);
              }));
}

export {
  get ,
  post ,
  Options ,
  Endpoints ,
  init ,
  
}
/* assets Not a pure module */
