// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var host = "http://localhost:8080";

var sandboxHost = "http://localhost:8080";

exports.host = host;
exports.sandboxHost = sandboxHost;
/* No side effect */
