// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var host = "https://pay.swipetech.io";

var sandboxHost = "https://pay.sandbox.swipetech.io";

exports.host = host;
exports.sandboxHost = sandboxHost;
/* No side effect */
